### ISSUE TITLE
Companies.getByDomain uri not found

### ISSUE THREAD

**Issue by antoineneff** [HGData/mk-node-hubspot#150]
Hey,

The request used to search companies by domain does not work anymore, the method and uri have changed.

Source : https://developers.hubspot.com/docs/methods/companies/search_companies_by_domain

**Comment by MattMSumner** [comment]
Has the old endpoint been deprecated? It appears that getByDomain is still working for me.

**Comment by pcothenet** [comment]
@antoineneff are you still having that issue?

**Comment by maxmedina05** [comment]
It's failing for me as well. It's actually making a GET request a now it's expecting a POST request.

Here's the error stack

```{ StatusCodeError: 404 - {"status":"error","message":"resource not found","correlationId":"4d6678cf-9944-489a-b19d-8953da927cf5","requestId":"7f9874eb0ee05fa8a28438f155fc1e52"}
    at new StatusCodeError (/Users/medma/Projects/data-sync/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/Users/medma/Projects/data-sync/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/Users/medma/Projects/data-sync/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/Users/medma/Projects/data-sync/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/Users/medma/Projects/data-sync/node_modules/request/request.js:1161:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/Users/medma/Projects/data-sync/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  name: 'StatusCodeError',
  statusCode: 404,
  message: '404 - {"status":"error","message":"resource not found","correlationId":"4d6678cf-9944-489a-b19d-8953da927cf5","requestId":"7f9874eb0ee05fa8a28438f155fc1e52"}',
  error: 
   { status: 'error',
     message: 'resource not found',
     correlationId: '4d6678cf-9944-489a-b19d-8953da927cf5',
     requestId: '7f9874eb0ee05fa8a28438f155fc1e52' },
  options: 
   { method: 'GET',
     json: true,
     resolveWithFullResponse: true,
     url: 'http://api.hubapi.com/companies/v2/companies/domain/gmail.com',
     qs: { hapikey: 'demo' },
     qsStringifyOptions: { arrayFormat: 'repeat' },
     timeout: 15000,
     callback: [Function: RP$callback],
     transform: undefined,
     simple: true,
     transform2xxOnly: false },
  response: 
   IncomingMessage {
     _readableState: 
      ReadableState {
        objectMode: false,
        highWaterMark: 16384,
        buffer: [Object],
        length: 0,
        pipes: null,
        pipesCount: 0,
        flowing: true,
        ended: true,
        endEmitted: true,
        reading: false,
        sync: true,
        needReadable: false,
        emittedReadable: false,
        readableListening: false,
        resumeScheduled: false,
        destroyed: false,
        defaultEncoding: 'utf8',
        awaitDrain: 0,
        readingMore: false,
        decoder: null,
        encoding: null },
     readable: false,
     domain: null,
     _events: 
      { end: [Array],
        close: [Array],
        data: [Function],
        error: [Function] },
     _eventsCount: 4,
     _maxListeners: undefined,
     socket: 
      Socket {
        connecting: false,
        _hadError: false,
        _handle: null,
        _parent: null,
        _host: 'api.hubapi.com',
        _readableState: [Object],
        readable: false,
        domain: null,
        _events: [Object],
        _eventsCount: 9,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: false,
        allowHalfOpen: false,
        _bytesDispatched: 137,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: null,
        _server: null,
        parser: null,
        _httpMessage: [Object],
        read: [Function],
        _consuming: true,
        _idleTimeout: -1,
        _idleNext: null,
        _idlePrev: null,
        _idleStart: 3204,
        _destroyed: false,
        [Symbol(asyncId)]: 19,
        [Symbol(bytesRead)]: 788,
        [Symbol(asyncId)]: 29,
        [Symbol(triggerAsyncId)]: 27 },
     connection: 
      Socket {
        connecting: false,
        _hadError: false,
        _handle: null,
        _parent: null,
        _host: 'api.hubapi.com',
        _readableState: [Object],
        readable: false,
        domain: null,
        _events: [Object],
        _eventsCount: 9,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: false,
        allowHalfOpen: false,
        _bytesDispatched: 137,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: null,
        _server: null,
        parser: null,
        _httpMessage: [Object],
        read: [Function],
        _consuming: true,
        _idleTimeout: -1,
        _idleNext: null,
        _idlePrev: null,
        _idleStart: 3204,
        _destroyed: false,
        [Symbol(asyncId)]: 19,
        [Symbol(bytesRead)]: 788,
        [Symbol(asyncId)]: 29,
        [Symbol(triggerAsyncId)]: 27 },
     httpVersionMajor: 1,
     httpVersionMinor: 1,
     httpVersion: '1.1',
     complete: true,
     headers: 
      { date: 'Wed, 05 Jun 2019 13:14:34 GMT',
        'content-type': 'application/json;charset=utf-8',
        'content-length': '151',
        connection: 'close',
        'set-cookie': [Array],
        'x-trace': '2B5930D68C0ECB46D35D66EE9FCB18D5B8981FB8AE000000000000000000',
        'x-hubspot-ratelimit-daily': '1000000',
        'x-hubspot-ratelimit-daily-remaining': '977604',
        'x-hubspot-ratelimit-secondly': '60',
        'x-hubspot-ratelimit-secondly-remaining': '58',
        'x-hubspot-notfound': 'true',
        'access-control-allow-credentials': 'false',
        server: 'cloudflare',
        'cf-ray': '4e22690acdefd70d-FRA' },
     rawHeaders: 
      [ 'Date',
        'Wed, 05 Jun 2019 13:14:34 GMT',
        'Content-Type',
        'application/json;charset=utf-8',
        'Content-Length',
        '151',
        'Connection',
        'close',
        'Set-Cookie',
        '__cfduid=dff629b01246348cdf5243ecd9e7d24aa1559740474; expires=Thu, 04-Jun-20 13:14:34 GMT; path=/; domain=.hubapi.com; HttpOnly',
        'X-Trace',
        '2B5930D68C0ECB46D35D66EE9FCB18D5B8981FB8AE000000000000000000',
        'X-HubSpot-RateLimit-Daily',
        '1000000',
        'X-HubSpot-RateLimit-Daily-Remaining',
        '977604',
        'X-HubSpot-RateLimit-Secondly',
        '60',
        'X-HubSpot-RateLimit-Secondly-Remaining',
        '58',
        'X-HubSpot-NotFound',
        'true',
        'Access-Control-Allow-Credentials',
        'false',
        'Server',
        'cloudflare',
        'CF-RAY',
        '4e22690acdefd70d-FRA' ],
     trailers: {},
     rawTrailers: [],
     upgrade: false,
     url: '',
     method: null,
     statusCode: 404,
     statusMessage: 'Not Found',
     client: 
      Socket {
        connecting: false,
        _hadError: false,
        _handle: null,
        _parent: null,
        _host: 'api.hubapi.com',
        _readableState: [Object],
        readable: false,
        domain: null,
        _events: [Object],
        _eventsCount: 9,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: false,
        allowHalfOpen: false,
        _bytesDispatched: 137,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: null,
        _server: null,
        parser: null,
        _httpMessage: [Object],
        read: [Function],
        _consuming: true,
        _idleTimeout: -1,
        _idleNext: null,
        _idlePrev: null,
        _idleStart: 3204,
        _destroyed: false,
        [Symbol(asyncId)]: 19,
        [Symbol(bytesRead)]: 788,
        [Symbol(asyncId)]: 29,
        [Symbol(triggerAsyncId)]: 27 },
     _consuming: true,
     _dumped: false,
     req: 
      ClientRequest {
        domain: null,
        _events: [Object],
        _eventsCount: 6,
        _maxListeners: undefined,
        output: [],
        outputEncodings: [],
        outputCallbacks: [],
        outputSize: 0,
        writable: true,
        _last: true,
        upgrading: false,
        chunkedEncoding: false,
        shouldKeepAlive: false,
        useChunkedEncodingByDefault: false,
        sendDate: false,
        _removedConnection: false,
        _removedContLen: false,
        _removedTE: false,
        _contentLength: 0,
        _hasBody: true,
        _trailer: '',
        finished: true,
        _headerSent: true,
        socket: [Object],
        connection: [Object],
        _header: 'GET /companies/v2/companies/domain/gmail.com?hapikey=demo HTTP/1.1\r\nhost: api.hubapi.com\r\naccept: application/json\r\nConnection: close\r\n\r\n',
        _onPendingData: [Function: noopPendingOutput],
        agent: [Object],
        socketPath: undefined,
        timeout: undefined,
        method: 'GET',
        path: '/companies/v2/companies/domain/gmail.com?hapikey=demo',
        _ended: true,
        res: [Circular],
        aborted: undefined,
        timeoutCb: [Function: emitTimeout],
        upgradeOrConnect: false,
        parser: null,
        maxHeadersCount: null,
        [Symbol(outHeadersKey)]: [Object] },
     request: 
      Request {
        domain: null,
        _events: [Object],
        _eventsCount: 5,
        _maxListeners: undefined,
        method: 'GET',
        resolveWithFullResponse: true,
        qsStringifyOptions: [Object],
        timeout: 15000,
        readable: true,
        writable: true,
        explicitMethod: true,
        _qs: [Object],
        _auth: [Object],
        _oauth: [Object],
        _multipart: [Object],
        _redirect: [Object],
        _tunnel: [Object],
        _rp_resolve: [Function],
        _rp_reject: [Function],
        _rp_promise: [Object],
        _rp_callbackOrig: undefined,
        callback: [Function],
        _rp_options: [Object],
        headers: [Object],
        setHeader: [Function],
        hasHeader: [Function],
        getHeader: [Function],
        removeHeader: [Function],
        localAddress: undefined,
        pool: {},
        dests: [],
        __isRequestRequest: true,
        _callback: [Function: RP$callback],
        uri: [Object],
        proxy: null,
        tunnel: false,
        setHost: true,
        originalCookieHeader: undefined,
        _disableCookies: true,
        _jar: undefined,
        port: 80,
        host: 'api.hubapi.com',
        url: [Object],
        path: '/companies/v2/companies/domain/gmail.com?hapikey=demo',
        _json: true,
        httpModule: [Object],
        agentClass: [Object],
        agent: [Object],
        _started: true,
        href: 'http://api.hubapi.com/companies/v2/companies/domain/gmail.com?hapikey=demo',
        req: [Object],
        ntick: true,
        timeoutTimer: null,
        response: [Circular],
        originalHost: 'api.hubapi.com',
        originalHostHeaderName: 'host',
        responseContent: [Circular],
        _destdata: true,
        _ended: true,
        _callbackCalled: true },
     toJSON: [Function: responseToJSON],
     caseless: Caseless { dict: [Object] },
     read: [Function],
     body: 
      { status: 'error',
        message: 'resource not found',
        correlationId: '4d6678cf-9944-489a-b19d-8953da927cf5',
        requestId: '7f9874eb0ee05fa8a28438f155fc1e52' } } }
```

**Comment by maxmedina05** [comment]
this is actually working again so this issue can be closed now.

**Comment by vkhomiv-hubspot** [comment]
Still seeing the issue.
Receiving error calling this method: 
`const companiesResponse = await hubspot.companies.getByDomain(domain);`

Error:
```
{ StatusCodeError: 404 - {"status":"error","message":"resource not found","requestId":"379f9624-d091-47a2-8ae0-03e3d8688277"}
    at new StatusCodeError (/Users/vkhomiv/projects/hubspot/hubspot-integration-samples-js/companies-app/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/Users/vkhomiv/projects/hubspot/hubspot-integration-samples-js/companies-app/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/Users/vkhomiv/projects/hubspot/hubspot-integration-samples-js/companies-app/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/Users/vkhomiv/projects/hubspot/hubspot-integration-samples-js/companies-app/node_modules/request/request.js:185:22)
    at Request.emit (events.js:182:13)
    at Request.<anonymous> (/Users/vkhomiv/projects/hubspot/hubspot-integration-samples-js/companies-app/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:182:13)
    at IncomingMessage.<anonymous> (/Users/vkhomiv/projects/hubspot/hubspot-integration-samples-js/companies-app/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:273:13)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1094:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  name: 'StatusCodeError',
  statusCode: 404,
  message:
   '404 - {"status":"error","message":"resource not found","requestId":"379f9624-d091-47a2-8ae0-03e3d8688277"}',
  error:
   { status: 'error',
     message: 'resource not found',
     requestId: '379f9624-d091-47a2-8ae0-03e3d8688277' },
  options:
   { method: 'GET',
     auth:
      { bearer:
         'CITMsfHYLRICAQMYuoSLAyC2oaAEKMmzDDIZAE2WU8pFE6Kjm1HtZfVuyUB0ji3AHbLGQDoPAAoiQQAADIADADgAAAAFQhkATZZTyqLgZxevbWM7T774nAcbTs1-Hbzw' },
     json: true,
     resolveWithFullResponse: true,
     url:
      'https://api.hubapi.com/companies/v2/companies/domain/bitbucket',
     qs: {},
     qsStringifyOptions: { arrayFormat: 'repeat' },
     timeout: 15000,
     callback: [Function: RP$callback],
     transform: undefined,
     simple: true,
     transform2xxOnly: false },
  response:
   IncomingMessage {
     _readableState:
      ReadableState {
        objectMode: false,
        highWaterMark: 16384,
        buffer: BufferList { head: null, tail: null, length: 0 },
        length: 0,
        pipes: null,
        pipesCount: 0,
        flowing: true,
        ended: true,
        endEmitted: true,
        reading: false,
        sync: true,
        needReadable: false,
        emittedReadable: false,
        readableListening: false,
        resumeScheduled: false,
        emitClose: true,
        destroyed: false,
        defaultEncoding: 'utf8',
        awaitDrain: 0,
        readingMore: true,
        decoder: null,
        encoding: null },
     readable: false,
     _events:
      { end: [Array],
        close: [Array],
        data: [Function],
        error: [Function] },
     _eventsCount: 4,
     _maxListeners: undefined,
     socket:
      TLSSocket {
        _tlsOptions: [Object],
        _secureEstablished: true,
        _securePending: false,
        _newSessionPending: false,
        _controlReleased: true,
        _SNICallback: null,
        servername: 'api.hubapi.com',
        alpnProtocol: false,
        authorized: true,
        authorizationError: null,
        encrypted: true,
        _events: [Object],
        _eventsCount: 7,
        connecting: false,
        _hadError: false,
        _handle: null,
        _parent: null,
        _host: 'api.hubapi.com',
        _readableState: [ReadableState],
        readable: false,
        _maxListeners: undefined,
        _writableState: [WritableState],
        writable: false,
        allowHalfOpen: false,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: undefined,
        _server: null,
        ssl: null,
        _requestCert: true,
        _rejectUnauthorized: true,
        parser: null,
        _httpMessage: [ClientRequest],
        timeout: 15000,
        [Symbol(res)]: null,
        [Symbol(asyncId)]: 291,
        [Symbol(lastWriteQueueSize)]: 0,
        [Symbol(timeout)]:
         Timeout {
           _called: false,
           _idleTimeout: -1,
           _idlePrev: null,
           _idleNext: null,
           _idleStart: 21955,
           _onTimeout: null,
           _timerArgs: undefined,
           _repeat: null,
           _destroyed: false,
           [Symbol(unrefed)]: true,
           [Symbol(asyncId)]: 301,
           [Symbol(triggerId)]: 299 },
        [Symbol(kBytesRead)]: 774,
        [Symbol(kBytesWritten)]: 276,
        [Symbol(connect-options)]: [Object] },
     connection:
      TLSSocket {
        _tlsOptions: [Object],
        _secureEstablished: true,
        _securePending: false,
        _newSessionPending: false,
        _controlReleased: true,
        _SNICallback: null,
        servername: 'api.hubapi.com',
        alpnProtocol: false,
        authorized: true,
        authorizationError: null,
        encrypted: true,
        _events: [Object],
        _eventsCount: 7,
        connecting: false,
        _hadError: false,
        _handle: null,
        _parent: null,
        _host: 'api.hubapi.com',
        _readableState: [ReadableState],
        readable: false,
        _maxListeners: undefined,
        _writableState: [WritableState],
        writable: false,
        allowHalfOpen: false,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: undefined,
        _server: null,
        ssl: null,
        _requestCert: true,
        _rejectUnauthorized: true,
        parser: null,
        _httpMessage: [ClientRequest],
        timeout: 15000,
        [Symbol(res)]: null,
        [Symbol(asyncId)]: 291,
        [Symbol(lastWriteQueueSize)]: 0,
        [Symbol(timeout)]:
         Timeout {
           _called: false,
           _idleTimeout: -1,
           _idlePrev: null,
           _idleNext: null,
           _idleStart: 21955,
           _onTimeout: null,
           _timerArgs: undefined,
           _repeat: null,
           _destroyed: false,
           [Symbol(unrefed)]: true,
           [Symbol(asyncId)]: 301,
           [Symbol(triggerId)]: 299 },
        [Symbol(kBytesRead)]: 774,
        [Symbol(kBytesWritten)]: 276,
        [Symbol(connect-options)]: [Object] },
     httpVersionMajor: 1,
     httpVersionMinor: 1,
     httpVersion: '1.1',
     complete: true,
     headers:
      { date: 'Wed, 02 Oct 2019 14:32:24 GMT',
        'content-type': 'application/json;charset=utf-8',
        'content-length': '100',
        connection: 'close',
        'set-cookie': [Array],
        'x-trace':
         '2B1B759B5647FBFE9389CC84E2482A40D0691D4657000000000000000000',
        'x-hubspot-notfound': 'true',
        vary: 'Accept-Encoding',
        'access-control-allow-credentials': 'false',
        'strict-transport-security': 'max-age=31536000; includeSubDomains; preload',
        'expect-ct':
         'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
        server: 'cloudflare',
        'cf-ray': '51f762aed8938428-KBP' },
     rawHeaders:
      [ 'Date',
        'Wed, 02 Oct 2019 14:32:24 GMT',
        'Content-Type',
        'application/json;charset=utf-8',
        'Content-Length',
        '100',
        'Connection',
        'close',
        'Set-Cookie',
        '__cfduid=d05d9b162d163057c6409a7fd6c5c79ad1570026744; expires=Thu, 01-Oct-20 14:32:24 GMT; path=/; domain=.hubapi.com; HttpOnly',
        'X-Trace',
        '2B1B759B5647FBFE9389CC84E2482A40D0691D4657000000000000000000',
        'X-HubSpot-NotFound',
        'true',
        'Vary',
        'Accept-Encoding',
        'Access-Control-Allow-Credentials',
        'false',
        'Strict-Transport-Security',
        'max-age=31536000; includeSubDomains; preload',
        'Expect-CT',
        'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
        'Server',
        'cloudflare',
        'CF-RAY',
        '51f762aed8938428-KBP' ],
     trailers: {},
     rawTrailers: [],
     aborted: false,
     upgrade: false,
     url: '',
     method: null,
     statusCode: 404,
     statusMessage: 'Not Found',
     client:
      TLSSocket {
        _tlsOptions: [Object],
        _secureEstablished: true,
        _securePending: false,
        _newSessionPending: false,
        _controlReleased: true,
        _SNICallback: null,
        servername: 'api.hubapi.com',
        alpnProtocol: false,
        authorized: true,
        authorizationError: null,
        encrypted: true,
        _events: [Object],
        _eventsCount: 7,
        connecting: false,
        _hadError: false,
        _handle: null,
        _parent: null,
        _host: 'api.hubapi.com',
        _readableState: [ReadableState],
        readable: false,
        _maxListeners: undefined,
        _writableState: [WritableState],
        writable: false,
        allowHalfOpen: false,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: undefined,
        _server: null,
        ssl: null,
        _requestCert: true,
        _rejectUnauthorized: true,
        parser: null,
        _httpMessage: [ClientRequest],
        timeout: 15000,
        [Symbol(res)]: null,
        [Symbol(asyncId)]: 291,
        [Symbol(lastWriteQueueSize)]: 0,
        [Symbol(timeout)]:
         Timeout {
           _called: false,
           _idleTimeout: -1,
           _idlePrev: null,
           _idleNext: null,
           _idleStart: 21955,
           _onTimeout: null,
           _timerArgs: undefined,
           _repeat: null,
           _destroyed: false,
           [Symbol(unrefed)]: true,
           [Symbol(asyncId)]: 301,
           [Symbol(triggerId)]: 299 },
        [Symbol(kBytesRead)]: 774,
        [Symbol(kBytesWritten)]: 276,
        [Symbol(connect-options)]: [Object] },
     _consuming: false,
     _dumped: false,
     req:
      ClientRequest {
        _events: [Object],
        _eventsCount: 6,
        _maxListeners: undefined,
        output: [],
        outputEncodings: [],
        outputCallbacks: [],
        outputSize: 0,
        writable: true,
        _last: true,
        chunkedEncoding: false,
        shouldKeepAlive: false,
        useChunkedEncodingByDefault: false,
        sendDate: false,
        _removedConnection: false,
        _removedContLen: false,
        _removedTE: false,
        _contentLength: 0,
        _hasBody: true,
        _trailer: '',
        finished: true,
        _headerSent: true,
        socket: [TLSSocket],
        connection: [TLSSocket],
        _header:
         'GET /companies/v2/companies/domain/bitbucket HTTP/1.1\r\nhost: api.hubapi.com\r\nauthorization: Bearer CITMsfHYLRICAQMYuoSLAyC2oaAEKMmzDDIZAE2WU8pFE6Kjm1HtZfVuyUB0ji3AHbLGQDoPAAoiQQAADIADADgAAAAFQhkATZZTyqLgZxevbWM7T774nAcbTs1-Hbzw\r\naccept: application/json\r\nConnection: close\r\n\r\n',
        _onPendingData: [Function: noopPendingOutput],
        agent: [Agent],
        socketPath: undefined,
        timeout: undefined,
        method: 'GET',
        path: '/companies/v2/companies/domain/bitbucket',
        _ended: true,
        res: [Circular],
        aborted: undefined,
        timeoutCb: [Function: emitRequestTimeout],
        upgradeOrConnect: false,
        parser: null,
        maxHeadersCount: null,
        [Symbol(isCorked)]: false,
        [Symbol(outHeadersKey)]: [Object] },
     request:
      Request {
        _events: [Object],
        _eventsCount: 5,
        _maxListeners: undefined,
        method: 'GET',
        resolveWithFullResponse: true,
        qsStringifyOptions: [Object],
        timeout: 15000,
        readable: true,
        writable: true,
        explicitMethod: true,
        _qs: [Querystring],
        _auth: [Auth],
        _oauth: [OAuth],
        _multipart: [Multipart],
        _redirect: [Redirect],
        _tunnel: [Tunnel],
        _rp_resolve: [Function],
        _rp_reject: [Function],
        _rp_promise: [Promise],
        _rp_callbackOrig: undefined,
        callback: [Function],
        _rp_options: [Object],
        headers: [Object],
        setHeader: [Function],
        hasHeader: [Function],
        getHeader: [Function],
        removeHeader: [Function],
        localAddress: undefined,
        pool: {},
        dests: [],
        __isRequestRequest: true,
        _callback: [Function: RP$callback],
        uri: [Url],
        proxy: null,
        tunnel: true,
        setHost: true,
        originalCookieHeader: undefined,
        _disableCookies: true,
        _jar: undefined,
        port: 443,
        host: 'api.hubapi.com',
        path: '/companies/v2/companies/domain/bitbucket',
        _json: true,
        httpModule: [Object],
        agentClass: [Function],
        agent: [Agent],
        _started: true,
        href:
         'https://api.hubapi.com/companies/v2/companies/domain/bitbucket',
        req: [ClientRequest],
        ntick: true,
        timeoutTimer: null,
        response: [Circular],
        originalHost: 'api.hubapi.com',
        originalHostHeaderName: 'host',
        responseContent: [Circular],
        _destdata: true,
        _ended: true,
        _callbackCalled: true },
     toJSON: [Function: responseToJSON],
     caseless: Caseless { dict: [Object] },
     body:
      { status: 'error',
        message: 'resource not found',
        requestId: '379f9624-d091-47a2-8ae0-03e3d8688277' } } }
```

**Comment by vkhomiv-hubspot** [comment]
I can confirm that client `hubspot.companies.getByDomain(domain)` method is outdated and uses wrong API url `GET /companies/v2/companies/domain/:domain` instead of `POST /companies/v2/domains/:domain/companies` according to Documentation here: https://developers.hubspot.com/docs/methods/companies/search_companies_by_domain
